#!/bin/bash


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi


read -p 'Are you sure you want to delete the chroot (y/N)? ' answer


if [ "$answer" == "Y" ] ;then
    echo Unmounting the chroot...
elif [ "$answer" == "y" ] ;then
    echo Unmounting the chroot...
else
    echo Not deleting the chroot
    exit
fi

unmount-fedora 2>/dev/null

echo Deleting the chroot...
rm -rf $location/fedora
rm -rf /usr/local/bin/enter-fedora
rm -rf /usr/local/bin/unmount-fedora
rm -rf /usr/local/bin/delete-fedora

echo Deleted the Fedora 31 Chroot
