#!/bin/bash


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
echo "Entering Fedora chroot"

script_name=$(basename -- "$0")
me=`basename "$0"`

mount -t proc proc $location/fedora/proc
mount -t sysfs sys $location/fedora/sys
mount -o bind /dev $location/fedora/dev
mount -o bind /dev/pts $location/fedora/dev/pts
mount -o ro,bind /etc/resolv.conf $location/etc/resolv.conf

chroot $location/fedora /bin/env -i \
    HOME=/root TERM="$TERM" PS1='[\u@f31chroot \W]\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/bin \
    sudo -u "#1000" /bin/bash --login
echo "Exiting Fedora chroot"

if pidof -x "$script_name" -o $$ >/dev/null;then
   echo "Not unmounting chroot because another instance is running"
   exit 1
else
   umount $location/fedora/proc
   umount -lf $location/fedora/proc
   umount $location/fedora/sys
   umount -lf $location/fedora/sys
   umount $location/fedora/dev/pts
   umount $location/fedora/dev
   umount -lf $location/fedora/dev/pts
   umount -lf $location/fedora/dev
   umount -lf $location/etc/resolv.conf
   sudo pkill "enter-fedora"
fi
echo "Cleaned up"
