#!/bin/bash


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi


if [ "$(mountpoint $location/fedora)" == "$location/fedora is a mountpoint" ]
  then echo "Entering Fedora chroot" 
else
  mount --bind $location/fedora $location/fedora
  mount -o remount,exec $location/fedora
  echo "Entering Fedora chroot"
fi

script_name=$(basename -- "$0")
me=`basename "$0"`

mount -t proc proc $location/fedora/proc 2>/dev/null
mount -t sysfs sys $location/fedora/sys 2>/dev/null
mount -o bind /dev $location/fedora/dev
mount -o bind /dev/pts $location/fedora/dev/pts
mount -o ro,bind /etc/resolv.conf $location/fedora/etc/resolv.conf

chroot $location/fedora /bin/env -i \
    HOME=/root TERM="$TERM" PS1='[\u@localhost \W]\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/bin \
    sudo -u "#1000" /bin/bash --login
echo "Exiting Fedora chroot"

if pidof -x "$script_name" -o $$ >/dev/null;then
   echo "Not unmounting chroot because another instance is running"
   umount $location/fedora/dev/pts
   umount $location/fedora/dev
   umount $location/fedora/etc/resolv.conf
   exit 1
else
unmount-fedora
fi
echo "Cleaned up"
