#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo "Where do you want to install the chroot?"

read -n prefix

cd $prefix

echo Downloading the Fedora 31 Docker Image

curl -L -o fedora.tar.xz http://fedora.mirror.constant.com/fedora/linux/releases/31/Container/x86_64/images/Fedora-Container-Base-31-1.9.x86_64.tar.xz 

tar xf fedora.tar.xz

echo Removing unnecessary files

rm -rf 1c*

rm -rf manifest.json

rm -rf repositories

mv ./5b* ./fedora

rm -rf fedora.tar.xz

cd fedora

rm -rf json

rm -rf VERSION

tar xf layer.tar

sudo rm -rf layer.tar

echo Setting up internet in the chroot

sudo rm -rf $prefix/fedora/etc/resolv.conf

sudo cp /etc/resolv.conf $prefix/fedora/etc

cd /usr/local/bin

curl -L -o enter-fedora https://raw.githubusercontent.com/Anonymoustank/Fedora-Installation/master/enter-fedora

sudo chmod +x enter-fedora

sudo chown -R root enter-fedora

sudo sed -i "2i "$prefix"" enter-fedora

sudo chroot $prefix/fedora curl -L -o setup.sh https://raw.githubusercontent.com/Anonymoustank/Fedora-Installation/master/setup.sh

sudo chroot $prefix/fedora chmod +x setup.sh

sudo chroot $prefix/fedora bash setup.sh

sudo rm -rf $prefix/fedora/setup.sh

echo Fedora 31 Installed! Use enter-fedora to enter the chroot

