#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

if [ "$(arch)" != "x86_64" ]
  then echo "This script only works for x86_64 devices"
  exit
fi

read -p 'Where do you want to install the chroot? ' prefix

mkdir $prefix 2>/dev/null

cd $prefix

echo Downloading the Fedora 31 Docker Image

curl -# -L -o fedora.tar.xz http://fedora.mirror.constant.com/fedora/linux/releases/31/Container/x86_64/images/Fedora-Container-Base-31-1.9.x86_64.tar.xz 

echo Extracting tarball

tar xf fedora.tar.xz

echo Removing unnecessary files

rm -rf 1c*

rm -rf manifest.json

rm -rf repositories

mv ./5b* ./fedora

rm -rf fedora.tar.xz

cd fedora

rm -rf json

rm -rf VERSION

tar xf layer.tar

rm -rf layer.tar

echo Setting up internet in the chroot

rm -rf $prefix/fedora/etc/resolv.conf

touch $prefix/fedora/etc/resolv.conf

mount -o ro,bind /etc/resolv.conf $prefix/fedora/etc/resolv.conf

cd /usr/local/bin

echo Installing additional scripts to /usr/local/bin

curl -L -o enter-fedora https://raw.githubusercontent.com/Anonymoustank/Fedora-Installation/master/enter-fedora 2>/dev/null

curl -L -o unmount-fedora https://raw.githubusercontent.com/Anonymoustank/Fedora-Installation/master/unmount-fedora 2>/dev/null

curl -L -o delete-fedora https://raw.githubusercontent.com/Anonymoustank/Fedora-Installation/master/delete-fedora 2>/dev/null

chmod +x delete-fedora

chmod +x enter-fedora

chmod +x unmount-fedora

sed -i "2i "location=$prefix"" enter-fedora

sed -i "2i "location=$prefix"" unmount-fedora

sed -i "2i "location=$prefix"" delete-fedora

cd $prefix/fedora

curl -L -o setup.sh https://raw.githubusercontent.com/Anonymoustank/Fedora-Installation/master/setup.sh 2>/dev/null

cd /usr/local/bin

chroot $prefix/fedora chmod +x setup.sh

chroot $prefix/fedora bash setup.sh

rm -rf $prefix/fedora/setup.sh

umount $prefix/fedora/etc/resolv.conf

umount $prefix/fedora

umount -lf $prefix/fedora 2>/dev/null

echo Fedora 31 Installed! Use enter-fedora to enter the chroot

echo Use delete-fedora to delete the chroot

