#!/bin/bash


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

umount $location/fedora/proc
umount $location/fedora/etc/resolv.conf
umount -lf $location/fedora/proc
umount $location/fedora/sys
umount -lf $location/fedora/sys
umount $location/fedora/dev/pts
umount $location/fedora/dev
umount -lf $location/fedora/dev/pts
umount -lf $location/fedora/dev
umount -lf $location/fedora/etc/resolv.conf
sudo pkill "enter-fedora"
