#!/bin/bash



if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi



function check_unmount {
  if [ "$(mountpoint $location/fedora/$1)" == "$location/fedora/$1 is a mountpoint" ]; then
  umount -lf $location/fedora/$1 2>/dev/null
fi
}


umount $location/fedora/proc 2>/dev/null
umount $location/fedora/etc/resolv.conf 2>/dev/null

check_unmount /proc 2>/dev/null

umount $location/fedora/sys 2>/dev/null

check_unmount /sys 2>/dev/null

umount $location/fedora/dev/pts 2>/dev/null

check_unmount /dev/pts 2>/dev/null

umount $location/fedora/dev 2>/dev/null

check_unmount /dev 2>/dev/null

check_unmount /etc/resolv.conf 2>/dev/null

umount $location/fedora 2>/dev/null

check_unmount / 2>/dev/null

pkill "enter-fedora" 2>/dev/null
